apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.android.support"  // atau com.xiepanda.modmenu
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        
        ndk {
            abiFilters 'armeabi-v7a'  // ARM32 ONLY
        }
        
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17 -fno-rtti -fno-exceptions -fpermissive'
                arguments '-DANDROID_STL=c++_shared'
            }
        }
    }
    
    externalNativeBuild {
        cmake {
            path "src/main/jni/CMakeLists.txt"
            // atau path "src/main/cpp/CMakeLists.txt"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.3.0'
}
